# Importando bibliotecas
import nltk
import streamlit as st

nltk.download('stopwords')
nltk.download('rslp')

# Título
st.write("""
**ANÁLISE DE SENTIMENTOS COM NLTK**\n
Este aplicativo utiliza técnicas de Machine Learning para realizar a análise de sentimentos positivos (Amor, Alegria e Felicidade) presentes nas frases disponibilizadas.\n

""")

# Dataset
# Bases de Treinamento e de Testes
basetreinamento = [
    
('você e adorável','amor'),
('adoro a maneira como você age','amor'),
('estou apaixonado','amor'),
('meu pai esta apaixonado','amor'),
('estamos todos encantados','amor'),
('essa situação e muito doce','amor'),
('disse adeus docemente','amor'),
('tenho simpatia por aquela pessoa','amor'),
('como pode ser tão simpática!','amor'),
('que maravilhoso seu encanto','amor'),
('tenho afeição por gente como você','amor'),
('isso tudo e só amor','amor'),
('me apaixono por suas verdades','amor'),
('tão agradável','amor'),
('isso me agrada completamente','amor'),
('te agrada isso','amor'),
('estou com sentimentos maravilhosos','amor'),
('todos estão enamorados','amor'),
('foi uma paixão incrível','amor'),
('isso e muito lindo','amor'),
('seja tão gentil','amor'),
('você fez uma manobra incrível','amor'),
('sua dignidade é impressionante','amor'),
('você e carinhoso com as crianças','amor'),
('que comentário amoroso','amor'),
('você lida com tudo com tanto respeito','amor'),
('sinto amor por você','amor'),
('e encantador a maneira como olha para as pessoas','amor'),
('estou disposta','amor'),
('a disposição me atacou hoje','amor'),
('acho que vou me apaixonar','amor'),
('tem muito amor lá','amor'),
('que prazer ter sua companhia','amor'),
('suas atitudes estão nos alegrando','amor'),
('que beleza olha toda essa perfeição','amor'),
('como isso está belo','amor'),
('tenho emoções só de lembrar','amor'),
('me sinto emocionada com o cheiro desta comida','amor'),
('você esta iluminando a passagem de ar','amor'),
('você esta maravilhosamente bem','amor'),
('olhe que bela esta roupa','amor'),
('que atitude adorável','amor'),
('nossa como você e bonito','amor'),
('muito bom tudo isso','amor'),
('estou encantado com você','amor'),
('você cortou o meu coração','amor'),
('esse perfume e encantador','amor'),
('ser amável não tem nada melhor','amor'),
('você e amável demais para minhas filhas','amor'),
('que cheiroso você esta','amor'),
('que cachorro cheiroso','amor'),
('e prazeroso da sua parte','amor'),
('situação agradável essa','amor'),
('tenho apreço a pessoas assim','amor'),
('amor e um bem da sociedade','amor'),
('que criatura adorável','amor'),
('e alegre a maneira como você vê o mundo','amor'),
('me agrada sua presença na festa','amor'),
('sinto amor por essa coisa','amor'),
('que lindo!','amor'),
('vou saborear o café agora','amor'),
('hora que garota encantadora!','amor'),
('estou apaixonada','amor'),
('isso que você disse foi muito maravilhoso','amor'),
('não seja obsceno na frente das crianças','amor'),
('esse assunto me da prazer','amor'),
('que criança maravilhosamente travessa','amor'),
('que criança bem educada','amor'),
('tão encantador, não tem nada mais bonito para dizer?','amor'),
('por motivo nobre e com emprego de meio amável','amor'),
('a admiração e tão nobre e honrosa que todos se atrevem a confessá-la','amor'),
('o incrível receio de ser sentimental e o mais honroso de todos os receios modernos','amor'),
('travesso gato quando fica com saudades do dono ronrona no sapato','amor'),
('isso e um ato adorável e corajoso','amor'),
('revelam apenas o que e construtivo e adorável para o povo','amor'),
('não sei como e a vida de um herói, mais a de um homem honesto e admirável','amor'),
('as virtudes do tempo e as justiças do homem','amor'),
('gracioso e humano','amor'),
('você publicará conteúdo amoroso, respeitoso e encorajador','amor'),
('afetuoso e expressivo','amor'),
('não há animal mais elevado, inteligente, corajoso, louvável, altruísta, respeitoso e admirável do que o homem','amor'),
('Se eu sei o que é amor, é por sua causa.','amor'),
('Você é a razão pela qual eu sorrio todos os dias.','amor'),
('Meu coração bate mais forte quando estou com você.','amor'),
('Seu abraço é o meu lugar favorito no mundo.','amor'),
('Você é o sonho que se tornou realidade.','amor'),
('Eu me apaixono por você todos os dias.','amor'),
('Você é a melhor coisa que já aconteceu na minha vida.','amor'),
('Nossas almas estão entrelaçadas para sempre.','amor'),
('Eu te amo mais do que as estrelas no céu.','amor'),
('Você ilumina minha vida como ninguém mais pode.','amor'),
('Juntos, somos um só coração e uma só alma.','amor'),
('Seu amor é a força que me move.','amor'),
('Eu não posso imaginar minha vida sem você.','amor'),
('Sua presença traz alegria e felicidade para o meu coração.','amor'),
('Eu te amo como o oceano ama a costa.','amor'),
('Nosso amor é uma história eterna.','amor'),
('Você é meu sol, minha lua e todas as minhas estrelas.','amor'),
('Seu amor me faz sentir completo.','amor'),
('Eu te amo mais do que posso expressar em palavras.','amor'),
('Você é a razão pela qual eu acredito no amor verdadeiro.','amor'),
('Nossos corações estão sempre sincronizados.','amor'),
('Eu te amarei até o fim dos tempos.','amor'),
('Você me faz querer ser uma pessoa melhor.','amor'),
('O amor que compartilhamos é a nossa maior aventura.','amor'),
('Nossas vidas se entrelaçaram como uma linda tapeçaria.','amor'),
('Eu te amo mais do que posso medir.','amor'),
('Você é minha inspiração e minha motivação.','amor'),
('O amor que sinto por você é infinito.','amor'),
('Você é a metade que completa meu coração.','amor'),
('Quando estou com você, o tempo parece parar.','amor'),
('Você me ensinou o verdadeiro significado do amor.','amor'),
('Nosso amor é como um farol, guiando-nos através da tempestade.','amor'),
('Seu amor é meu tesouro mais precioso.','amor'),
('Você é a chama que aquece meu coração.','amor'),
('Eu te amo mais a cada dia que passa.','amor'),
('Você é a música que meu coração canta.','amor'),
('Meu amor por você não conhece limites.','amor'),
('Você é a luz que ilumina minha vida.','amor'),
('Eu te amo mais do que qualquer coisa neste mundo.','amor'),
('Nossos corações estão sempre conectados, não importa a distância.','amor'),
('Você é minha âncora em um mar agitado.','amor'),
('Meu amor por você é como um rio, sempre fluindo e sempre crescendo.','amor'),
('Você é a razão pela qual eu me sinto vivo.','amor'),
('Nossas almas foram feitas para se encontrar e se amar.','amor'),
('Você é meu porto seguro em um mundo incerto.','amor'),
('Eu te amarei até meu último suspiro.','amor'),
('Você é a essência do meu ser.','amor'),
('Nosso amor é como uma chama eterna, nunca se apagando.','amor'),
('Você é o ar que eu respiro e o amor que eu preciso.','amor'),
('O amor que compartilhamos é maior que a vida.','amor'),
('Você me faz sentir como se estivesse nas nuvens.','amor'),
('Nossos corações batem em uníssono, uma melodia de amor verdadeiro.','amor'),
('Eu te amarei através de todos os altos e baixos da vida.','amor'),
('Você é meu refúgio em meio à tempestade.','amor'),
('Nosso amor é como um jardim, sempre florescendo e sempre crescendo.','amor'),
('Você é a estrela que guia meu caminho.','amor'),
('Eu te amo mais do que o universo pode conter.','amor'),
('Você me completa de uma maneira que ninguém mais pode.','amor'),
('Nosso amor é uma jornada que vale a pena percorrer.','amor'),
('Você é a fonte da minha felicidade e alegria.','amor'),
('Eu te amarei em todas as estações da vida.','amor'),
('Seu amor é o sol que ilumina minhas manhãs e a lua que ilumina minhas noites.','amor'),
('Você é meu parceiro, meu melhor amigo e meu amor verdadeiro.','amor'),
    ('Nosso amor é uma chama que nunca se apaga.','amor'),
    ('Eu te amo como a abelha ama a flor.','amor'),
    ('Você é a chave que desbloqueia meu coração.','amor'),
    ('Nosso amor é um vínculo indestrutível que nos une.','amor'),
    ('Você é a luz do meu mundo e o calor do meu coração.','amor'),
    ('Eu te amarei em todas as vidas que vivermos juntos.','amor'),
    ('Seu amor é como uma brisa suave que acaricia minha alma, trazendo paz e contentamento.','amor'),
    ('Você é o pilar que me sustenta em tempos difíceis.','amor'),
    ('Eu te amo mais do que todas as estrelas no céu e todos os grãos de areia na praia.','amor'),
    ('Você é a pessoa que faz meu coração saltar de alegria.','amor'),
    ('Nosso amor é a ponte que nos conecta, não importa a distância.','amor'),
    ('Eu te amarei até o fim da eternidade.','amor'),
    ('Você é a canção que meu coração nunca se cansa de cantar.','amor'),
    ('Nosso amor é o vento, não podemos vê-lo, mas podemos senti-lo.','amor'),
    ('Eu te amo como a planta ama a chuva que a nutre.','amor'),
    ('Você é o tesouro que encontrei no fim do arco-íris.','amor'),
    ('Eu te amarei em todas as encarnações que possamos ter.','amor'),
    ('Seu amor é como um raio de sol em um dia chuvoso.','amor'),
    ('Você é o combustível que alimenta minha paixão e minha devoção.','amor'),
    ('Nosso amor é uma tapeçaria de momentos mágicos e memórias inesquecíveis.','amor'),
('Eu te amo como a lua ama a noite.','amor'),
('Nosso amor é um fogo que arde intensamente, iluminando nossas vidas.','amor'),
('Você é o toque mágico que transforma minha vida em uma obra de arte.','amor'),
('Eu te amarei além do fim dos tempos e do espaço.','amor'),
('Seu amor é o oásis que sacia minha sede em um deserto árido.','amor'),
('Você é a melodia que embala meu coração em harmonia.','amor'),
('Nosso amor é uma sinfonia de emoções, paixões e ternura.','amor'),
('Eu te amo como a terra ama o sol que a aquece.','amor'),
('Você é a inspiração que me faz sonhar e acreditar no impossível.','amor'),
('Eu te amarei até que as estrelas parem de brilhar e o tempo pare de fluir.','amor'),
('Nosso amor é um porto seguro, onde podemos ancorar nossos corações e almas.','amor'),
('Você é a peça que faltava no quebra-cabeça do meu coração.','amor'),
('Nosso amor é uma história eterna, escrita nas estrelas e selada em nossos corações.','amor'),
('Seu amor é como uma brisa suave que acaricia minha alma, trazendo paz e contentamento.','amor'),
('Você é a luz que ilumina meu caminho, mesmo nos momentos mais escuros.','amor'),
                  

('é bom ouvir sua voz','alegria'),
('contentamento é a palavra que define meu estado de espírito','alegria'),
('estou acompanhado por bons amigos','alegria'),
('estou animada','alegria'),
('ele esta todo animado','alegria'),
('tão alegres suas palavras','alegria'),
('seu amor agora é meu','alegria'),
('isso vai me alegrar','alegria'),
('estou com muita alegria','alegria'),
('me alegra o modo como fala','alegria'),
('estou em êxtase com meu íntimo','alegria'),
('quero fazer tudo','alegria'),
('me sinto animada e cheia de vida','alegria'),
('não consigo parar de sorrir','alegria'),
('é muita alegria ter um ente querido','alegria'),
('estou realmente satisfeita','alegria'),
('acho que o karma volta, pois agora sou eu quem celebra','alegria'),
('você cumpriu suas promessas','alegria'),
('me sinto revigorada','alegria'),
('já é tarde demais para ficar triste','alegria'),
('essa noite alegra só para mim','alegria'),
('você mudou para melhor','alegria'),
('quando eu penso em você realmente me enche de alegria','alegria'),
('como se fosse nada você vê meu sorriso','alegria'),
('você disse carinhosamente que não se arrependeu','alegria'),
('eu sempre vou te ver','alegria'),
('ela está muito feliz','alegria'),
('estar alegre é muito bom','alegria'),
('estou realizada e radiante depois deste dia','alegria'),
('é comovente te ver dessa maneira','alegria'),
('é comovente ver o que os filhos do Brasil conquistam','alegria'),
('como me sinto orgulhosa','alegria'),
('estou radiante','alegria'),
('a tranquilidade tomou conta de mim','alegria'),
('as pessoas gostam do meu jeito','alegria'),
('até logo passamos bons momentos juntos','alegria'),
('sinto alegria','alegria'),
('ele adorou a minha comida','alegria'),
('estou com dinheiro para a comida','alegria'),
('queria que fosse sempre o melhor dia da minha vida','alegria'),
('você está orgulhoso de mim','alegria'),
('ela aceitou a minha proposta','alegria'),
('era o meu último centavo bem gasto','alegria'),
('passei de ano na faculdade','alegria'),
('afinal você só sabe me elogiar','alegria'),
('eu fui muito elogiado','alegria'),
('é uma história muito alegre','alegria'),
('todos acreditam em mim','alegria'),
('eu sirvo para tudo mesmo','alegria'),
('ufa, faço tudo direito','alegria'),
('fui promovida essa semana','alegria'),
('as crianças se alegram ainda mais que os adultos','alegria'),
('pra mim um dia é bom, o outro é melhor','alegria'),
('de repente ganhei o apetite','alegria'),
('estamos afundados em alegria','alegria'),
('nem um milagre pode nos tirar a felicidade','alegria'),
('só me resta aproveitar','alegria'),
('melhor que isso não pode ficar','alegria'),
('meu salário é alto','alegria'),
('passei no vestibular','alegria'),
('todos se importam comigo','alegria'),
('todos lembraram do meu aniversário','alegria'),
('tenho tanto sorte','alegria'),
('o gosto da alegria é doce','alegria'),
('estou animada com a vida','alegria'),
('é um ânimo só coitadinha','alegria'),
('a vitória é alegre','alegria'),
('incentivar é humano','alegria'),
('que ânimo','alegria'),
('é uma honra para o país','alegria'),
('o otimismo nos levar a ação','alegria'),
('passamos ao encorajamento e à lucidez','alegria'),
('cuidado com a alegria ela é contagiante','alegria'),
('A alegria de viver está em compartilhar a vida com quem se ama.','alegria'),
('Faça do presente a sua alegria.','alegria'),
('A alegria da vida só existe para quem tem coragem.','alegria'),
('A alegria de viver está em sentir gratidão.','alegria'),
('A vida é uma viagem, desfrute o caminho.','alegria'),
('A alegria da vida não está nas coisas, está em nós.','alegria'),
('Pra vida eu só quero um coração regado de alegria.','alegria'),
('Sinta alegria e agradeça por tudo que tem na vida.','alegria'),
('A alegria e o amor estão dentro de você para preenchê-los.','alegria'),
('Faça a dieta da alegria: um sorriso a cada manhã, um agradecimento ao final do dia.','alegria'),
('E que não nos falte alguém para multiplicar nossas alegrias e diminuir nossa tristeza.','alegria'),
('A alegria evita mil males e prolonga a vida.','alegria'),
('A alegria está em prestar atenção nos detalhes da vida.','alegria'),
('As pequenas alegrias do dia a dia são as mais preciosas.','alegria'),
('Alegria é você sentir o sol entrar.','alegria'),
('Em simples momentos se encontram grandes alegrias.','alegria'),
('Alegria compartilhada é alegria redobrada.','alegria'),
('Aqui só cabe alegria!','alegria'),


('Estou radiante de felicidade, minha equipe ganhou o campeonato!','felicidade'),
('Nada me faz mais feliz do que ver o pôr do sol na praia.','felicidade'),
('Consegui o emprego dos meus sonhos, estou nas nuvens!','felicidade'),
('Que alegria saber que todos estão seguros e saudáveis.','felicidade'),
('Hoje é um dia incrível para celebrar a vida e a felicidade.','felicidade'),
('Estou tão feliz que consegui realizar meu sonho de viajar para o exterior.','felicidade'),
('Recebi uma notícia maravilhosa que encheu meu coração de alegria.','felicidade'),
('Sinto uma felicidade imensa ao estar rodeado de amigos e familiares.','felicidade'),
('Cada momento ao lado da pessoa amada é uma fonte inesgotável de felicidade.','felicidade'),
('Ganhei um prêmio inesperado e estou pulando de felicidade!','felicidade'),
('A felicidade transborda quando vejo o sorriso no rosto das crianças.','felicidade'),
('Hoje é um daqueles dias em que tudo dá certo, estou extremamente feliz!','felicidade'),
('Realizei um feito que parecia impossível, estou nas nuvens de felicidade.','felicidade'),
('A sensação de conquistar meus objetivos é simplesmente incrível.','felicidade'),
('Mal posso conter a felicidade ao receber tantos elogios pelo meu trabalho.','felicidade'),
('Estou tão feliz que até as estrelas parecem brilhar mais intensamente.','felicidade'),
('A alegria de estar cercado por pessoas que amo é indescritível.','felicidade'),
('Hoje é um daqueles dias que vou guardar na memória para sempre.','felicidade'),
('Agradeço por cada momento de felicidade que a vida me proporciona.','felicidade'),
('O simples fato de estar vivo já é motivo suficiente para ser feliz.','felicidade'),
('Sinto uma imensa gratidão por todas as bênçãos que a vida me oferece.','felicidade'),
('A felicidade está nas pequenas coisas, como um abraço apertado.','felicidade'),
('A realização de um sonho é como um raio de sol iluminando meu coração.','felicidade'),
('A felicidade é contagiosa, e hoje ela se espalhou por todos os lados.','felicidade'),
('Saber que faço a diferença na vida de alguém me enche de alegria.','felicidade'),
('Viver o presente com gratidão é a chave para uma vida plena de felicidade.','felicidade'),
('A felicidade não tem preço, e hoje estou rico de momentos especiais.','felicidade'),
('Cada dia é uma nova oportunidade de ser feliz, e eu aproveito ao máximo.','felicidade'),
('Estou tão feliz que meu coração parece querer pular para fora do peito.','felicidade'),
('A felicidade é um estado de espírito, e o meu está radiante hoje.','felicidade'),
('A vida é uma jornada repleta de momentos felizes, e eu celebro cada um deles.','felicidade'),
('A felicidade está em abraçar o presente.','felicidade'),
('A felicidade de uma xícara de café quente pela manhã.','felicidade'),
('A felicidade está em compartilhar risadas com amigos.','felicidade'),
('A felicidade de uma criança brincando despreocupada.','felicidade'),
('A felicidade está em encontrar beleza na simplicidade.','felicidade'),
('A felicidade de um pôr do sol deslumbrante.','felicidade'),
('A felicidade está em abraçar a gratidão.','felicidade'),
('A felicidade de ver um sorriso genuíno.','felicidade'),
('A felicidade está em desfrutar de uma refeição deliciosa.','felicidade'),
('A felicidade de receber elogios sinceros.','felicidade'),
('A felicidade está em fazer o que você ama.','felicidade'),
('A felicidade de realizar um sonho de infância.','felicidade'),
('A felicidade está em viver no momento presente.','felicidade'),
('A felicidade de estar rodeado de pessoas que você ama.','felicidade'),
('A felicidade está em compartilhar momentos especiais.','felicidade'),
('A felicidade de se apaixonar.','felicidade'),
('A felicidade está em encontrar significado na vida.','felicidade'),
('A felicidade de dançar quando ninguém está assistindo.','felicidade'),
('A felicidade está em abraçar a liberdade de ser você mesmo.','felicidade'),
('A felicidade de superar desafios e alcançar objetivos.','felicidade'),
('A felicidade está em ser grato pelo que você tem.','felicidade'),
('A felicidade de passar tempo ao ar livre em um dia ensolarado.','felicidade'),
('A felicidade está em abraçar a jornada da vida.','felicidade'),
('A felicidade de fazer uma boa ação.','felicidade'),
('A felicidade está em abraçar a simplicidade da vida.','felicidade'),
('A felicidade de ver o florescer da primavera.','felicidade'),
('A felicidade está em celebrar conquistas.','felicidade'),
('A felicidade de viajar e explorar o mundo.','felicidade'),
('A felicidade está em fazer alguém sorrir.','felicidade'),
('A felicidade de se perder em um bom livro.','felicidade'),
('A felicidade está em encontrar a paz interior.','felicidade'),
('A felicidade de rir até doer a barriga.','felicidade'),
('A felicidade está em viver com um coração grato.','felicidade'),
('A felicidade de ouvir sua música favorita.','felicidade'),
('A felicidade está em abraçar a diversão.','felicidade'),
('A felicidade de receber uma surpresa inesperada.','felicidade'),
('Felicidade é quando o que você pensa, o que você diz e o que você faz estão em harmonia.','felicidade'),
('Não há felicidade mais verdadeira do que aquela que experimentamos ao alcançar um sonho.','felicidade'),
('A felicidade não é algo que se alcança depois de uma longa caminhada, é a viagem toda.','felicidade'),
('Ser feliz é também cair nas tentações da vida de vez em quando.','felicidade'),
('A felicidade depende mais de você mesmo do que todos os eventos do mundo.','felicidade'),
('Sorrir é capaz de mudar realidades.','felicidade'),
('Está esperando o quê para abraçar, ser feliz e viver intensamente.','felicidade'),
('Não importa o que você decidiu, o que importa é que isso te faça feliz.','felicidade'),
('Que a vontade de ser feliz seja sempre maior que o medo de se machucar.','felicidade'),
('O segredo da felicidade é não dar importância ao que não tem importância.','felicidade'),
('Não existe um caminho para a felicidade, a felicidade é o caminho.','felicidade'),
('Que a felicidade seja sonho, meta e realidade.','felicidade'),
('Coloque felicidade no topo da sua lista de prioridades.','felicidade'),
('A felicidade não depende do que nos falta, mas do bom uso do que temos.','felicidade'),
('Que o vento sopre sempre a favor da felicidade!','felicidade'),
('Que a felicidade faça a gente de gato e sapato!','felicidade'),
('Dar risada me deixa feliz.','felicidade'),
('Rir até a barriga doer de tanta felicidade.','felicidade'),
('Um sorriso sincero é um gesto de felicidade.','felicidade'),
('A estrela da felicidade encontrei a primeira vez que eu te beijei.','felicidade'),
('Um dia sem risada é um dia desperdiçado.','felicidade'),
('Que o vento leve, que a chuva lave, que a alma brilhe, que o coração acalme, que a harmonia se instale e a felicidade permaneça.','felicidade'),
('Ser feliz sem motivo é a mais autêntica forma de felicidade.','felicidade'),
('Sonhe muito, ria alto, a ordem dos fatores não altera a felicidade.','felicidade'),
('O melhor lugar do mundo é sempre ao lado de quem te proporciona felicidade.','felicidade'),
('Aí vem a vida e te vira do avesso, apenas para provar que a felicidade vem de dentro para fora.','felicidade'),
('Vamos cuidar de ser ainda mais felizes.','felicidade'),
('Que a felicidade sempre seja forte e intensa, mesmo que não seja em abundância.','felicidade'),
('Mentalize a felicidade e ela virá até você.','felicidade'),
('Qualquer coisa pode mudar e se tornar uma fonte de felicidade, acredite.','felicidade'),
('Deu um lindo sorriso de felicidade.','felicidade'),
('Um sorriso negro, um abraço negro. Traz felicidade.','felicidade'),
('Negro é a raiz da felicidade.','felicidade'),
('A felicidade não se encontra, se sente.','felicidade'),
('Seja feliz como você é.','felicidade'),
('Espalhe o bem que a felicidade vem.','felicidade'),
('Nasci para ser feliz.','felicidade'),
('Que os dias felizes sejam os mais longos.','felicidade'),
('Alimente todos os dias a sua vontade de ser feliz.','felicidade')
]

baseteste =[
('Seu sorriso é a coisa mais linda que já vi.','amor'),
('Cada momento ao seu lado é como um sonho realizado.','amor'),
('Meu coração transborda de amor por você.','amor'),
('Sua presença ilumina meus dias e aquece meu coração.','amor'),
('O amor que sinto por você é mais forte que qualquer adversidade.','amor'),
('Seu abraço é o meu lugar seguro, onde encontro paz e felicidade.','amor'),
('Nunca imaginei que pudesse amar alguém tão intensamente.','amor'),
('Você é a pessoa que completa o meu mundo e faz tudo ter sentido.','amor'),
('Cada pequeno gesto seu é um lembrete do quanto eu te amo.','amor'),
('A cada dia que passa, meu amor por você só cresce.','amor'),
('Você é a razão do meu sorriso e a fonte da minha felicidade.','amor'),
('Ao seu lado, cada momento se torna especial e inesquecível.','amor'),
('Nossa história de amor é a mais linda que já vivi.','amor'),
('Seu amor é o combustível que me impulsiona a ser uma pessoa melhor.','amor'),
('A simples ideia de te perder me parte o coração.','amor'),
('Você é meu porto seguro, meu amor eterno.','amor'),
('Cada dia ao seu lado é uma bênção que agradeço todos os dias.','amor'),
('Meu coração pertence a você e a mais ninguém.','amor'),
('A maneira como você me olha faz meu coração acelerar.','amor'),
('Com você, descobri o verdadeiro significado do amor.','amor'),
('Nossas almas se encontraram e se apaixonaram profundamente.','amor'),
('Sua presença é a luz que ilumina os dias mais escuros.','amor'),
('Agradeço todos os dias por ter você ao meu lado.','amor'),
('Você é a pessoa dos meus sonhos, meu amor eterno.','amor'),
('Cada segundo contigo é um presente que guardo no coração.','amor'),
('Meu amor por você é eterno, como o céu infinito.','amor'),
('A vida ao seu lado é uma jornada repleta de amor e felicidade.','amor'),
('O amor que sinto por você é a força que move minha vida.','amor'),
('Nada se compara à felicidade que você me proporciona.','amor'),
('Seu amor é a música que embala a trilha sonora da minha vida.','amor'),
('Ao seu lado, descobri o verdadeiro significado da plenitude.','amor'),
('Cada detalhe seu é motivo para eu me apaixonar ainda mais.','amor'),
('Você é o sonho que nunca soube que tinha, meu amor.','amor'),
('Amar você é a melhor escolha que já fiz na vida.','amor'),


('Estou radiante de alegria com essa notícia maravilhosa!','alegria'),
('Cada conquista me enche de alegria e gratidão.','alegria'),
('A felicidade transborda quando estou cercado por quem amo.','alegria'),
('Esse momento de vitória é a razão da minha alegria.','alegria'),
('Estou tão feliz que parece que vou voar de tanta alegria!','alegria'),
('Nada supera a alegria de estar ao lado das pessoas que amo.','alegria'),
('A alegria de viver intensamente é o segredo da felicidade.','alegria'),
('Recebi uma surpresa que encheu meu coração de alegria.','alegria'),
('Meu coração transborda de alegria e gratidão por este momento.','alegria'),
('A alegria de ver um sonho realizado é indescritível.','alegria'),
('A alegria de compartilhar conquistas é a mais pura felicidade.','alegria'),
('Cada pequena vitória é motivo para celebrar e espalhar alegria.','alegria'),
('A alegria de estar com quem amamos é o maior presente da vida.','alegria'),
('A alegria é a trilha sonora da minha vida.','alegria'),
('Estou tão feliz que meu coração parece querer pular de alegria.','alegria'),
('A alegria de viver o presente é o segredo para uma vida plena.','alegria'),
('A alegria de encontrar amigos verdadeiros é incomparável.','alegria'),
('Estou vivendo um momento de alegria intensa e contagiante.','alegria'),
('Cada dia ao seu lado é uma festa de alegria e amor.','alegria'),
('A alegria de realizar sonhos é a melhor sensação do mundo.','alegria'),
('A alegria está nas pequenas coisas, como um abraço apertado.','alegria'),
('A alegria de superar desafios é o que torna a vida emocionante.','alegria'),
('Estou radiante de alegria por alcançar meus objetivos.','alegria'),
('A alegria de ser quem sou é o que me impulsiona todos os dias.','alegria'),
('A alegria de fazer o bem é o que dá significado à minha vida.','alegria'),
('Estou transbordando de alegria com as boas notícias que recebi.','alegria'),
('A alegria de ter amigos leais é um tesouro incomparável.','alegria'),
('A alegria de amar e ser amado é a essência da vida.','alegria'),
('A cada sorriso, sinto a alegria iluminar meu coração.','alegria'),
('A alegria de estar cercado por pessoas positivas é contagiante.','alegria'),
('A alegria de aprender e crescer faz parte da jornada da vida.','alegria'),


('Que felicidade encontrar você aqui!', 'felicidade'),
('Estou radiante de felicidade com essa notícia incrível!', 'felicidade'),
('A alegria que sinto é indescritível!', 'felicidade'),
('Estou transbordando de felicidade com essa realização.','felicidade'),
('Cada momento ao seu lado é um pedaço de felicidade.','felicidade'),
('A felicidade de alcançar meus objetivos é imensa.','felicidade'),
('A felicidade está estampada no meu rosto hoje.','felicidade'),
('Sua presença traz uma onda de felicidade para minha vida.','felicidade'),
('Que alegria saber que todos estão bem e saudáveis.','felicidade'),
('A felicidade de compartilhar boas notícias é contagiante.','felicidade'),
('Estou tão feliz que meu coração parece querer pular de alegria!','felicidade'),
('A alegria de viver o presente é o segredo para uma vida plena.','felicidade'),
('A alegria de realizar sonhos é a melhor sensação do mundo.','felicidade'),
('A alegria está nas pequenas coisas, como um abraço apertado.','felicidade'),
('A felicidade de superar desafios é o que torna a vida emocionante.','felicidade'),
('Estou radiante de felicidade por alcançar meus objetivos.','felicidade'),
('A felicidade de ser quem sou é o que me impulsiona todos os dias.','felicidade'),
('A felicidade de fazer o bem é o que dá significado à minha vida.','felicidade'),
('Estou transbordando de felicidade com as boas notícias que recebi.','felicidade'),
('A felicidade de ter amigos leais é um tesouro incomparável.','felicidade'),
('A felicidade de amar e ser amado é a essência da vida.','felicidade'),
('A cada sorriso, sinto a felicidade iluminar meu coração.','felicidade'),
('A felicidade de estar cercado por pessoas positivas é contagiante.','felicidade'),
('A felicidade de aprender e crescer faz parte da jornada da vida.','felicidade')]

base = [
    ('eu sou admirada por muitos', 'alegria'),
    ('me sinto completamente amado', 'amor'),
    ('amar é maravilhoso', 'amor'),
    ('estou me sentindo muito animado novamente', 'alegria'),
    ('eu estou muito bem hoje', 'alegria'),
    ('que belo dia para dirigir um carro novo', 'alegria'),
    ('o dia está muito bonito', 'alegria'),
    ('estou contente com o resultado do teste que fiz ontem', 'alegria'),
    ('o amor é lindo', 'amor'),
    ('nossa amizade e amor vai durar para sempre', 'amor'),
    ('estou amedrontado', 'medo'),
    ('ele está me ameaçando há dias', 'medo'),
    ('isso me deixa apavorada', 'medo'),
    ('este lugar é apavorante', 'medo'),
    ('se perdermos outro jogo seremos eliminados e isso me deixa com pavor', 'medo'),
    ('tome cuidado com o lobisomem', 'medo'),
    ('se eles descobrirem estamos encrencados', 'medo'),
    ('estou tremendo de medo', 'medo'),
    ('eu tenho muito medo dele', 'medo'),
    ('estou com medo do resultado dos meus testes', 'medo')
]

stopwordsnltk = nltk.corpus.stopwords.words('portuguese')
stopwordsnltk.append('vou')
stopwordsnltk.append('tão')


def aplicastemmer(texto):
    stemmer = nltk.stem.RSLPStemmer()
    frasessstemming = []
    for (palavras, emocao) in texto:
        comstemming = [str(stemmer.stem(p)) for p in palavras.split() if p not in stopwordsnltk]
        frasessstemming.append((comstemming, emocao))
    return frasessstemming


frasescomstemmingtreinamento = aplicastemmer(basetreinamento)
frasescomstemmingteste = aplicastemmer(baseteste)


def buscapalavras(frases):
    todaspalavras = []
    for (palavras, emocao) in frases:
        todaspalavras.extend(palavras)
    return todaspalavras


palavras = buscapalavras(frasescomstemmingteste)


def buscafrequencia(palavras):
    palavras = nltk.FreqDist(palavras)
    return palavras


frequencia = buscafrequencia(palavras)


def buscapalavrasunicas(frequencia):
    freq = frequencia.keys()
    return freq


palavrasunicas = buscapalavrasunicas(frequencia)


def extratorpalavras(documento):
    doc = set(documento)
    caracteristicas = {}
    for palavras in palavrasunicas:
        caracteristicas['%s' % palavras] = (palavras in doc)
    return caracteristicas


basecompletatreinamento = nltk.classify.apply_features(extratorpalavras, frasescomstemmingtreinamento)
basecompletateste = nltk.classify.apply_features(extratorpalavras, frasescomstemmingteste)

classificador = nltk.NaiveBayesClassifier.train(basecompletatreinamento)


st.subheader('Análise de Sentimento')

texto_input = st.text_input('Insira o texto para análise (Aperte enter para enviar): ')

stemmer = nltk.stem.RSLPStemmer()
texto_processado = [str(stemmer.stem(p)) for p in texto_input.split() if p not in stopwordsnltk]
caracteristicas_usuario = extratorpalavras(texto_processado)

sentimento = classificador.classify(caracteristicas_usuario)

st.subheader('Sentimento do Texto:')
st.success(sentimento)

